# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
